//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Status { get; set; }
        public int OwnerId { get; set; }
        public Nullable<int> DeliveryDriverId { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> PaymentId { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Users DeliveryDrivers { get; set; }
        public virtual Users Owners { get; set; }
        public virtual Payments Payments { get; set; }
    }
}
